# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f47765a4768aa3dfa5f7cc351d8b0185a48380ad59659b3ee4e4e26a7ae10696702c014d6f328477f144d2e4ccd6c591032330ccb231559d7b064b4f9ada00af

test:
  secret_key_base: 4157591d4f5938e6a6a7e15e48aff6eb5fb204892aaebefd18f750583af96414bf224c46269a2bb7f6ffbf9e95043d3c85a90831ba631c1d2f0cb73faeea0cd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
